version: '3.7'
services:
    httpd:
        build: httpd/.
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ssl:/usr/local/apache2/conf/ssl
        environment:
            TZ: America/Chicago
        networks:
            app_net:
                ipv4_address: 10.0.0.2
    tomcat:
        build: tomcat/.
        expose:
            - "8009"
            - "8080"
        volumes:
            - dbsign:/opt/dbsign
        environment:
            TZ: America/Chicago
        networks:
            app_net:
                ipv4_address: 10.0.0.3
    mysql:
        build: mysql/.
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Qwerty_123
            MYSQL_DATABASE: dbsign
            MYSQL_USER: dbsign
            MYSQL_PASSWORD: Qwerty_123
            TZ: America/Chicago
        networks:
            app_net:
                ipv4_address: 10.0.0.4
    #The following was an attempt to create an isolated GUI container for running the DBsign Admin Tools
    #vnc:
    #    build: vnc/.
    #    ports:
    #        - "5999:5901"
    #    environment:
    #        VNC_PASSWORD: Qwerty_123
    #        TZ: America/Chicago
    #    networks:
    #        app_net:
    #            ipv4_address: 10.0.0.5
volumes:
    database:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/volumes/database'
    dbsign:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/volumes/dbsign'
    ssl:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/volumes/ssl'
networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/24"
